---
project:
  title: Supuestamente
  description: "esto no esta pasando..."
  version: "3.0"
  rapydo: "3.0"
  

variables:
  # roles:
  #   normal_user: YourCustomName
  #   staff_user: YourCustomName
  #   # staff_user: disabled
  #   group_coordinator: YourCustomName
  #   admin_root: YourCustomName
  #   extra_role: YourExtraRole

  # roles_descriptions:
  #   normal_user: User Custom Description
  #   staff_user: Staff Custom Description
  #   group_coordinator: Group Coordinator Custom Description
  #   admin_root: Administrator Custom Description
  #   extra_role: Custom Role Description

  submodules:
    http-api:
      branch: 3.0
    rapydo-angular:
      branch: 3.0
    do:
      branch: 3.0
  env:

    ACTIVATE_AUTH: 0
    FRONTEND_FRAMEWORK: angular
    ACTIVATE_ALCHEMY: 1
    ACTIVATE_POSTGRES: 1
    ACTIVATE_FASTAPI: 1
    ACTIVATE_FTP: 1
     
